//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyParticleGunMessenger_h
#define MyParticleGunMessenger_h 1

#include "G4UImessenger.hh"
#include "globals.hh"

class MyParticleGun;

class G4UIdirectory;
class G4UIcmdWithAString;
class G4UIcmdWithAnInteger;
class G4UIcmdWithADouble;
class G4UIcmdWithADoubleAndUnit;
class G4UIcmdWith3Vector;
class G4UIcmdWith3VectorAndUnit;
class G4UIcmdWithoutParameter;

class MyParticleGunMessenger : public G4UImessenger
{
public:
    MyParticleGunMessenger(MyParticleGun *);
    ~MyParticleGunMessenger();

    virtual void SetNewValue(G4UIcommand *, G4String);

private:
    MyParticleGun *gunAction;

    //#PartGun 4. 定义粒子枪的命令
    G4UIcmdWithAString *fBGFileNameCmd;
    G4UIcmdWithoutParameter *fGunTypeCmd;
};

#endif
