//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef SimEvent_h
#define SimEvent_h

#include "TVector3.h"
#include "TObject.h"
#include "TMap.h"
#include "TObjString.h"
#include "Verbose.hh"
#include <map>

class SimEvent : public TObject
{

public:
    SimEvent() { MyClear(); }
    virtual ~SimEvent() {}

    void MyClear()
    {
        stored = 0;
        //hit.clear();
        eng.clear();
    }
    /*
    void SetHitInfo(G4ThreeVector _hpos, G4ThreeVector _hmom, G4RotationMatrix _rot, G4ThreeVector _tran, G4ThreeVector _norm, G4double _ang)
    {
        if (!stored)
        {
            hitPos = _hpos;
            hitMom = _hmom;
            rotation = _rot;
            translation = _tran;
            normal = _norm;
            incidenceAngle = _ang;
            stored = 1;
        }
    }
    void StoreHit(G4ThreeVector _hpos, G4double _eng)
    {
        hit.push_back(&_hpos);
        eng.push_back(_eng);
    }
    */

public:
    bool stored;
    //G4ThreeVector hitPos;
    //G4ThreeVector hitMom;
    //G4RotationMatrix rotation;
    //G4ThreeVector translation;
    //G4ThreeVector normal;
    double incidenceAngle;

    //std::vector<G4ThreeVector* > hit;
    std::vector<double> eng;

};

#endif
