//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyActionInitialization_h
#define MyActionInitialization_h 1

#include "G4VUserActionInitialization.hh"

/// Action initialization class.
class MyDetectorConstruction;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

class MyActionInitialization : public G4VUserActionInitialization
{
public:
    MyActionInitialization(MyDetectorConstruction *);
    virtual ~MyActionInitialization();

    virtual void BuildForMaster() const;
    virtual void Build() const;

private:
    MyDetectorConstruction *fDetectorConstruction;
};

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

#endif
