//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef Verbose_hh
#define Verbose_hh
extern int verbose;  //0, mean no output; !=0, means output user defined messages
#endif
