//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyStackAction_h
#define MyStackAction_h 1

#include "G4UserStackingAction.hh"
#include "globals.hh"

class G4LogicalVolume;
class MyStackAction : public G4UserStackingAction
{
public:
  MyStackAction();
  ~MyStackAction();

  void SetKillStatus(G4int value) { fKillSecondary = value; };

  virtual G4ClassificationOfNewTrack ClassifyNewTrack(const G4Track *);
	int comptcout = 0;

private:
  G4int fKillSecondary;
};

#endif
