//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyTrackAction_h
#define MyTrackAction_h 1

#include "G4UserTrackingAction.hh"
#include "globals.hh"

class MyTrackAction : public G4UserTrackingAction
{
public:
  MyTrackAction();
  virtual ~MyTrackAction();
};

#endif