//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#include "MyActionInitialization.hh"
#include "MyGunAction.hh"
#include "MyGunAction.hh"
#include "MyRunAction.hh"
#include "MyEvtAction.hh"
#include "MyStepAction.hh"
#include "MyStackAction.hh"
#include "MyTrackAction.hh"
#include "Verbose.hh"

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

MyActionInitialization::MyActionInitialization()
    : G4VUserActionInitialization()
{
  if (verbose)
    G4cout << "====>MyActionInitialization::MyActionInitialization()" << G4endl;
	masterGPS = new G4GeneralParticleSource();
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

MyActionInitialization::~MyActionInitialization()
{
	delete masterGPS;
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

void MyActionInitialization::BuildForMaster() const
{
  if (verbose)
    G4cout << "====>MyActionInitialization::BuildForMaster()" << G4endl;

  SetUserAction(new MyRunAction());
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......

void MyActionInitialization::Build() const
{
  if (verbose)
    G4cout << "====>MyActionInitialization::Build()" << G4endl;

  SetUserAction(MyGunAction::GetInstance());

  SetUserAction(new MyEvtAction());

  SetUserAction(new MyRunAction());

  SetUserAction(new MyStepAction());

  SetUserAction(new MyStackAction());

  SetUserAction(new MyTrackAction());
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
