//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#include "G4TrackingManager.hh"
#include "G4Track.hh"
#include "Verbose.hh"

#include "MyTrackAction.hh"

MyTrackAction::MyTrackAction()
    : G4UserTrackingAction()
{
  if (verbose)
    G4cout << "====>MyTrackAction::MyTrackAction()" << G4endl;
}

MyTrackAction::~MyTrackAction()
{
}