//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyRunAction_h
#define MyRunAction_h 1

#include "G4UserRunAction.hh"
#include "MyDetectorConstruction.hh"
#include "globals.hh"

class MyAnalysisMessenger;
class G4Run;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

class MyRunAction : public G4UserRunAction
{
public:
    MyRunAction(MyDetectorConstruction *);
    virtual ~MyRunAction();

    virtual void BeginOfRunAction(const G4Run *run);
    virtual void EndOfRunAction(const G4Run *run);

private:
    MyAnalysisMessenger *fRunMessenger;
    MyDetectorConstruction *fDetector;
};

#endif
